bug fix  with myfirst commit
emmanueltct/MyBrand_BE pull request #2
Opened 2024-02-19 10:57 UTC by emmanueltct

I pushed here all code in my local repository for progress review

2024-02-19 13:21 UTC, Eli250 requested changes

2024-02-19 13:21 UTC, Eli250 commented on dist/Models/blogComment.js
>      return (mod && mod.__esModule) ? mod : { "default": mod };
You shouldn't push dist folder, there is no need. Add dist directory to gitignore.

2024-02-19 13:21 UTC, Eli250 commented on README.md
> -MyBrand portfolio backend part
You need to update your readme file. Include your project title, overview of your project, and how we can manually test your project.

2024-02-20 07:50 UTC, emmanueltct commented on README.md
> -MyBrand portfolio backend part
I worked on it and update my read me file

2024-02-20 07:51 UTC, emmanueltct commented on dist/Models/blogComment.js
>      return (mod && mod.__esModule) ? mod : { "default": mod };
I added it to gitignore

2024-02-20 08:26 UTC, merged