project files restructuring
emmanueltct/MyBrand_BE pull request #3
Opened 2024-02-21 11:20 UTC by emmanueltct

the following are changes made to my  project
1. change the folder structure of my file
2. creating middleware for each entity (blogs, comments, and Querries)
3. add dist folder to gitignore
4. implement validation for Cloudinary image uploader
5. customizing status code return message for my endpoints 
6. protecting my endpoints for authorized or authenticated access and making the public access to others

2024-02-21 14:52 UTC, Eli250 requested changes

2024-02-21 14:52 UTC, Eli250 commented on .env
>  dbURL="mongodb+srv://emmanuelmunezero:AndelaCohort29@cluster0.prj6gh4.mongodb.net/?retryWrites=true&w=majority"
You shouldn't be pushing the environment variables. Add this file in .gitignore file.

2024-02-21 14:52 UTC, Eli250 commented on src/controllers/blogsComment.ts
> +        console.log(req.user)
Remove this unnecessary log.

2024-02-21 14:52 UTC, Eli250 commented on src/controllers/blogsComment.ts
> +            res.status(400).json({error:"we are validating you before you place a comment and something went wrong"})
Your message doens't make sense. Also use proper http status code.

2024-02-21 14:52 UTC, Eli250 commented on src/controllers/blogsComment.ts
>      }
Always make sure that you return a response. use 'return' to mark the end of the process.

2024-02-21 14:52 UTC, Eli250 commented on src/controllers/blogsComment.ts
> +        res.status(400).json({ error: "comments doesn't exist!" })
Wrong http status code.

2024-02-21 14:52 UTC, Eli250 commented on src/controllers/blogsComment.ts
>      }
You are not using the right http status. It has to be 404 in case it is not found.

2024-02-22 08:39 UTC, emmanueltct reviewed
I made changes to my project according to feedback review and the following are changes in my code
1. add .env file to gitignore
2. customize my status code to match with endpoint response
3. add a return key word to each end point response

2024-02-26 13:29 UTC, merged